*** Settings ***
Library    SeleniumLibrary
Library    OperatingSystem
Library    DateTime
Library    Process
Suite Setup       Load Environment Variables
Suite Teardown    Close Browser
Library    Collections

*** Variables ***
${URL}        http://192.168.203.92:8080/CVWeb/cvLgn
${BROWSER}    edge
${USERNAME}   ${EMPTY}
${PASSWORD}   ${EMPTY}
# PATH FIX: was hardcoded to a personal C:\Users\ctn_ravi\Downloads\dms_bot\Folder_1 --
# repointed to the app's real staging folder (matches DMS_PENDING_UPLOAD_FOLDER in the
# current dms_upload.robot / config.DMS_STAGING_FOLDER). This is where
# services/rf_queue_worker.py's _process_gate_in() drops h{id}_...pdf files.
${INVOICE_SOURCE_PATH}    C:\\material_inward\\dms_staging
# PATH FIX: was hardcoded to a personal C:\Users\ctn_ravi\Downloads\dms_bot\Folder_2 --
# repointed to the app's real archive folder (matches DMS_UPLOADED_ARCHIVE_FOLDER in the
# current dms_upload.robot).
${INVOICE_PROCESSED_PATH}    C:\\material_inward\\dms_staging\\uploaded
# PATH FIX: added -- was missing entirely in this draft, so links generated by
# Process All Document Links had nowhere configured to land. Loaded from .env below,
# same as the current dms_upload.robot, so services/dms_links_import.py reads from the
# same file this writes to. Do not hardcode this -- see that script's docstring.
${DMS_LINKS_EXCEL_PATH}   ${EMPTY}

*** Keywords ***

Load Environment Variables
    ${env_path}=    Join Path    ${EXECDIR}    .env
    Evaluate    __import__('dotenv').load_dotenv(r'''${env_path}''')
    ${USERNAME}=    Evaluate    __import__('os').getenv('CV_USERNAME')
    ${PASSWORD}=    Evaluate    __import__('os').getenv('CV_PASSWORD')
    # PATH FIX: added -- load DMS_LINKS_EXCEL_PATH the same way the current
    # dms_upload.robot does, instead of leaving Save File Name And Link To Excel
    # writing to a hardcoded personal path with no history_id matching downstream.
    ${LINKS_PATH}=    Evaluate    __import__('os').getenv('DMS_LINKS_EXCEL_PATH')
    Should Not Be Empty    ${USERNAME}
    Should Not Be Empty    ${PASSWORD}
    Should Not Be Empty    ${LINKS_PATH}
    Set Suite Variable    ${USERNAME}
    Set Suite Variable    ${PASSWORD}
    Set Suite Variable    ${DMS_LINKS_EXCEL_PATH}    ${LINKS_PATH}

Open Login Page
    Open Browser    ${URL}    ${BROWSER}
    Maximize Browser Window
    Sleep    8s

Handle YES Popup
    Log    🔔 Session popup detected — clicking YES
    ${yes_found}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible
    ...    xpath=//button[normalize-space()='YES']    3s
    Run Keyword If    ${yes_found}
    ...    Click Element    xpath=//button[normalize-space()='YES']
    ...    ELSE    Execute Javascript
    ...    var allElements = document.querySelectorAll('button, input[type=button], a');
    ...    for(var i=0; i<allElements.length; i++){
    ...        if(allElements[i].textContent.trim().toUpperCase() === 'YES'){
    ...            allElements[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    2s
    Log    ✅ YES clicked — session popup closed

Login To Contentverse
    Execute Javascript
    ...    var inputs = document.querySelectorAll('input');
    ...    for(var i=0; i<inputs.length; i++){
    ...        if(inputs[i].placeholder && inputs[i].placeholder.toLowerCase().includes('user')){
    ...            inputs[i].value = '${USERNAME}';
    ...            inputs[i].dispatchEvent(new Event('input', {bubbles:true}));
    ...            inputs[i].dispatchEvent(new Event('change', {bubbles:true}));
    ...        }
    ...    }
    Sleep    1s
    Execute Javascript
    ...    var inputs = document.querySelectorAll('input');
    ...    for(var i=0; i<inputs.length; i++){
    ...        if(inputs[i].placeholder && inputs[i].placeholder.toLowerCase().includes('password')){
    ...            inputs[i].value = '${PASSWORD}';
    ...            inputs[i].dispatchEvent(new Event('input', {bubbles:true}));
    ...            inputs[i].dispatchEvent(new Event('change', {bubbles:true}));
    ...        }
    ...    }
    Sleep    1s
    Execute Javascript
    ...    var inputs = document.querySelectorAll('input');
    ...    for(var i=0; i<inputs.length; i++){
    ...        if(inputs[i].placeholder && inputs[i].placeholder.toLowerCase().includes('room')){
    ...            inputs[i].value = 'SPL.DMS';
    ...            inputs[i].dispatchEvent(new Event('input', {bubbles:true}));
    ...            inputs[i].dispatchEvent(new Event('change', {bubbles:true}));
    ...            inputs[i].dispatchEvent(new Event('keyup', {bubbles:true}));
    ...        }
    ...    }
    Sleep    3s
    ${dropdown_visible}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible    xpath=//*[contains(text(),'SPL.DMS')]    5s
    Run Keyword If    ${dropdown_visible}
    ...    Click Element    xpath=//*[contains(text(),'SPL.DMS')]
    Sleep    1s
    Execute Javascript
    ...    var buttons = document.querySelectorAll('button');
    ...    for(var i=0; i<buttons.length; i++){
    ...        if(buttons[i].textContent.trim().toUpperCase().includes('LOG IN')){
    ...            buttons[i].click();
    ...            break;
    ...        }
    ...    }
    FOR    ${i}    IN RANGE    10
        Sleep    1s
        ${popup_found}=    Run Keyword And Return Status
        ...    Page Should Contain    already active
        Run Keyword If    ${popup_found}    Handle YES Popup
        Run Keyword If    ${popup_found}    Exit For Loop
    END
    Sleep    5s

Get Current Month Folder Name
    ${date}=    Get Current Date    result_format=%Y-%b
    [Return]    ${date}

Get Current Year Folder Name
    ${year}=    Get Current Date    result_format=%Y
    [Return]    ${year}

Expand Material Inward Process
    Wait Until Element Is Visible
    ...    xpath=//*[contains(text(),'Material Inward Process')]    10s
    Sleep    1s
    ${mip_element}=    Get WebElement
    ...    xpath=//*[contains(text(),'Material Inward Process')]
    Mouse Over    ${mip_element}
    Sleep    1s
    ${plus_clicked}=    Run Keyword And Return Status
    ...    Click Element
    ...    xpath=//*[contains(text(),'Material Inward Process')]/preceding-sibling::*[1]
    Run Keyword Unless    ${plus_clicked}
    ...    Execute Javascript
    ...    var els = document.querySelectorAll('*');
    ...    for(var i=0; i<els.length; i++){
    ...        if(els[i].innerText && els[i].innerText.trim() === 'Material Inward Process'){
    ...            var parent = els[i].parentElement;
    ...            if(parent && parent.firstElementChild){
    ...                parent.firstElementChild.click();
    ...            }
    ...            break;
    ...        }
    ...    }
    Sleep    3s
    ${mip_visible}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible
    ...    xpath=//*[contains(text(),'MIP Docs')]    5s
    Run Keyword Unless    ${mip_visible}
    ...    Execute Javascript
    ...    var els = document.querySelectorAll('*');
    ...    for(var i=0; i<els.length; i++){
    ...        if(els[i].innerText && els[i].innerText.trim() === 'Material Inward Process'){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    3s
    Log    ✅ Expand done

Expand MIP Docs
    Wait Until Element Is Visible
    ...    xpath=//*[contains(text(),'MIP Docs')]    10s
    Sleep    1s
    ${mip_docs_element}=    Get WebElement
    ...    xpath=//*[contains(text(),'MIP Docs')]
    Mouse Over    ${mip_docs_element}
    Sleep    1s
    Run Keyword And Ignore Error
    ...    Click Element
    ...    xpath=//*[contains(text(),'MIP Docs')]/preceding-sibling::*[1]
    Sleep    2s

Right Click Folder Node
    [Arguments]    ${node_locator}
    Wait Until Element Is Visible    ${node_locator}    10s
    Sleep    1s
    ${node_element}=    Get WebElement    ${node_locator}
    Open Context Menu    ${node_element}
    Sleep    2s

Click Create Folder From Menu
    Sleep    1s
    ${exists}=    Execute Javascript
    ...    return document.getElementById('createNodeAnchorMobile') != null;
    Log To Console    Exists=${exists}
    Execute Javascript
    ...    document.getElementById('createNodeAnchorMobile').click();

Type Folder Name And Click Ok
    [Arguments]    ${folder_name}
    Sleep    2s
    Execute Javascript
    ...    var inputs = document.querySelectorAll('input[type="text"], input:not([type])');
    ...    for(var i=0; i<inputs.length; i++){
    ...        if(inputs[i].offsetParent !== null && inputs[i].value === ''){
    ...            inputs[i].value = '${folder_name}';
    ...            inputs[i].dispatchEvent(new Event('input', {bubbles:true}));
    ...            inputs[i].dispatchEvent(new Event('change', {bubbles:true}));
    ...            break;
    ...        }
    ...    }
    Sleep    1s
    Press Keys    NONE    TAB
    Sleep    1s
    Press Keys    NONE    RETURN

Check If Folder Already Exists
    [Arguments]    ${folder_name}
    ${exists}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible
    ...    xpath=//*[text()='${folder_name}']    3s
    [Return]    ${exists}

Create Folder If Not Exists
    [Arguments]    ${parent_locator}    ${folder_name}
    ${folder_exists}=    Check If Folder Already Exists    ${folder_name}
    Run Keyword If    ${folder_exists}
    ...    Log    ⚠️ Folder '${folder_name}' already exists. Skipping.
    ...    ELSE    Run Keywords
    ...    Right Click Folder Node    ${parent_locator}
    ...    AND    Click Create Folder From Menu
    ...    AND    Type Folder Name And Click Ok    ${folder_name}

Check If Subfolder Already Exists
    [Arguments]    ${parent_name}    ${folder_name}
    Expand Folder Node    ${parent_name}
    ${exists}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible
    ...    xpath=//a[text()='${parent_name}']/parent::li//a[text()='${folder_name}']    3s
    [Return]    ${exists}

Create Subfolder If Not Exists
    [Arguments]    ${parent_locator}    ${parent_name}    ${folder_name}
    ${folder_exists}=    Check If Subfolder Already Exists    ${parent_name}    ${folder_name}
    Run Keyword If    ${folder_exists}
    ...    Log    ⚠️ Folder '${folder_name}' already exists under '${parent_name}'. Skipping.
    ...    ELSE    Run Keywords
    ...    Right Click Folder Node    ${parent_locator}
    ...    AND    Click Create Folder From Menu
    ...    AND    Type Folder Name And Click Ok    ${folder_name}

Open Subfolder By Name
    [Arguments]    ${parent_name}    ${folder_name}
    Expand Folder Node    ${parent_name}
    ${locator}=    Set Variable
    ...    xpath=//a[text()='${parent_name}']/parent::li//a[text()='${folder_name}']
    Wait Until Element Is Visible    ${locator}    10s
    Click Element    ${locator}
    Sleep    2s

Get List Of Invoice Files
    ${files}=    List Files In Directory    ${INVOICE_SOURCE_PATH}    *.pdf    absolute=False
    [Return]    ${files}

Open Folder By Name
    [Arguments]    ${folder_name}
    Wait Until Element Is Visible    xpath=//*[text()='${folder_name}']    10s
    Click Element    xpath=//*[text()='${folder_name}']
    Sleep    2s

Check If Invoice Already Exists
    [Arguments]    ${invoice_name}
    ${exists}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible
    ...    xpath=//td[normalize-space(text())='${invoice_name}'] | //*[@class='docName' and normalize-space(text())='${invoice_name}'] | //span[normalize-space(text())='${invoice_name}']    5s
    [Return]    ${exists}

Expand Folder Node
    [Arguments]    ${folder_name}
    Wait Until Element Is Visible
    ...    xpath=//a[text()='${folder_name}']    10s
    ${already_open}=    Run Keyword And Return Status
    ...    Page Should Contain Element
    ...    xpath=//a[text()='${folder_name}']/ancestor::li[1][contains(@class,'jstree-open')]
    IF    not ${already_open}
        ${node_element}=    Get WebElement
        ...    xpath=//a[text()='${folder_name}']
        Mouse Over    ${node_element}
        Sleep    1s
        ${arrow_clicked}=    Run Keyword And Return Status
        ...    Click Element
        ...    xpath=//a[text()='${folder_name}']/preceding-sibling::*[1]
        IF    not ${arrow_clicked}
            Execute Javascript
            ...    var els = document.querySelectorAll('a');
            ...    for(var i=0; i<els.length; i++){
            ...        if(els[i].textContent.trim() === '${folder_name}'){
            ...            var li = els[i].closest('li');
            ...            if(li){
            ...                var arrow = li.querySelector('.jstree-ocl, ins, i');
            ...                if(arrow){ arrow.click(); }
            ...            }
            ...            break;
            ...        }
            ...    }
        END
        Sleep    2s
    END

Click New Document Tab
    Execute Javascript
    ...    var els = document.querySelectorAll('a, li, button, span');
    ...    for(var i=0; i<els.length; i++){
    ...        var txt = els[i].textContent.trim().toUpperCase();
    ...        if((txt.includes('BATCH') || txt.includes('SCANNING') || txt.includes('IMPORT'))
    ...            && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    3s

Upload New Invoices
    [Arguments]    @{file_paths}

    FOR    ${file_path}    IN    @{file_paths}
        ${filename}=    Evaluate    __import__('os').path.basename(r'${file_path}')
        ${report_name}=    Evaluate    __import__('os').path.splitext('${filename}')[0]

        Log    📄 Processing: ${filename} → ReportName: ${report_name}

        Click Bulk Upload Option
        Sleep    2s

        # Step 1: Open the "+" dropdown (sets New Document context — keep this)
        Execute Javascript
        ...    var btn = document.getElementById('createDoc');
        ...    if(btn){ btn.click(); }
        Sleep    1s

        # Step 1b: DIAGNOSTIC — dump the dropdown HTML so we can see real selectors if this still fails
        ${dropdown_html}=    Execute Javascript
        ...    var els = document.querySelectorAll('.dropDownElement, ul, div');
        ...    for (var i=0; i<els.length; i++){
        ...        if (els[i].textContent.indexOf('Browse') > -1 && els[i].offsetParent !== null){
        ...            return els[i].outerHTML;
        ...        }
        ...    }
        ...    return 'NOT FOUND';
        Create File    ${EXECDIR}/browse_dropdown_debug.html    ${dropdown_html}
        Log    🔍 Dumped dropdown HTML to browse_dropdown_debug.html

        # Step 2 (REPLACED): Do NOT click "Browse..." — that fires the native OS dialog and hangs Selenium.
        # Instead, resolve the real hidden file input directly via JS.
        ${file_input_id}=    Execute Javascript
        ...    var preferred = document.getElementById('viewDocumentAddPagesMobile');
        ...    var target = preferred;
        ...    if(!target || target.offsetParent === null && !target){
        ...        var inputs = document.querySelectorAll('input[type="file"]');
        ...        for (var i=0; i<inputs.length; i++){ target = inputs[i]; }
        ...    }
        ...    if(!target){ return 'NONE'; }
        ...    if(!target.id){ target.id = 'cv_resolved_file_input'; }
        ...    target.style.cssText = 'opacity:1 !important; position:relative !important;'
        ...        + 'width:200px !important; height:30px !important;'
        ...        + 'display:block !important; visibility:visible !important;'
        ...        + 'top:0 !important; left:0 !important; z-index:9999 !important;';
        ...    return target.id;
        Log    📌 Resolved file input id: ${file_input_id}
        Should Not Be Equal As Strings    ${file_input_id}    NONE
        ...    msg=No <input type="file"> found on the New Document panel — check browse_dropdown_debug.html
        Sleep    1s

        # Step 4: Upload the file directly on the resolved input
        Choose File    id=${file_input_id}    ${file_path}
        Sleep    3s

        # Step 5: Handle size popup if it appears
        ${size_popup_present}=    Run Keyword And Return Status
        ...    Page Should Contain    exceeds the global file viewing limit
        IF    ${size_popup_present}
            Log    ⚠️ Size popup appeared — clicking Download    console=yes
            Execute Javascript
            ...    var buttons = document.querySelectorAll('button, a, input[type=button]');
            ...    for (var i=0; i<buttons.length; i++){
            ...        if (buttons[i].textContent.trim().toUpperCase() === 'DOWNLOAD'
            ...            && buttons[i].offsetParent !== null){
            ...            buttons[i].click(); break;
            ...        }
            ...    }
            Sleep    2s
        END

        # Step 6: Dismiss any leftover modal
        Execute Javascript
        ...    var modals = document.querySelectorAll('.cvModel');
        ...    for(var i=0; i<modals.length; i++){
        ...        modals[i].style.display = 'none';
        ...    }
        Sleep    1s

        # Step 7: Select CVReports from Document Type dropdown
        Execute Javascript
        ...    var selects = document.querySelectorAll('select');
        ...    for(var i=0; i<selects.length; i++){
        ...        var opts = selects[i].options;
        ...        for(var j=0; j<opts.length; j++){
        ...            if(opts[j].text.trim() === 'CVReports'){
        ...                selects[i].selectedIndex = j;
        ...                selects[i].dispatchEvent(new Event('change', {bubbles:true}));
        ...                break;
        ...            }
        ...        }
        ...    }
        Sleep    3s

        # Step 8: Fill ReportName field
        Debug Dump Report Name Panel HTML
        Wait Until Element Is Visible
        ...    xpath=//*[contains(text(),'ReportName')]/ancestor::tr[1]//input[not(@id='signInput')]    10s
        ${input_el}=    Get WebElement
        ...    xpath=//*[contains(text(),'ReportName')]/ancestor::tr[1]//input[not(@id='signInput')]
        Clear Element Text    ${input_el}
        Input Text    ${input_el}    ${report_name}
        Sleep    1s
        Press Keys    ${input_el}    TAB
        Sleep    2s

        # Step 9: Click Create
        Wait Until Element Is Visible     xpath=//button[normalize-space()='Create']    10s
        Wait Until Element Is Enabled     xpath=//button[normalize-space()='Create']    10s
        Scroll Element Into View          xpath=//button[normalize-space()='Create']
        Sleep    1s

        ${clicked}=    Run Keyword And Return Status
        ...    Click Element    xpath=//button[normalize-space()='Create']
        Log To Console    CREATE CLICK STATUS = ${clicked}
        Capture Page Screenshot    after_create_click.png
        Sleep    5s

        Log    ✅ Done: ${filename}
    END

Debug Dump Report Name Panel HTML
    ${html}=    Execute Javascript    return document.body.innerHTML;
    Create File    ${EXECDIR}/report_panel_debug.html    ${html}

Close Document Viewer
    Debug Dump Document Viewer HTML
    ${info}=    Execute Javascript
    ...    var candidates = document.querySelectorAll('span, a, button, i, div, ins');
    ...    var target = null;
    ...    for (var i=0; i<candidates.length; i++){
    ...        var el = candidates[i];
    ...        var txt = (el.textContent || '').trim();
    ...        var cls = (el.className || '').toLowerCase();
    ...        var title = (el.title || '').toLowerCase();
    ...        if ((txt === '\u00d7' || cls.indexOf('close') > -1 || title.indexOf('close') > -1) && el.offsetParent !== null){
    ...            target = el; break;
    ...        }
    ...    }
    ...    if(!target) return 'NONE';
    ...    var desc = target.tagName + ' | class=' + target.className + ' | title=' + target.title + ' | text=' + target.textContent.trim();
    ...    target.click();
    ...    return desc;
    Log    🔍 Close-button click target: ${info}
    Sleep    2s


Reopen Month Folder After Upload
    [Arguments]    ${year_folder}    ${month_folder}
    Sleep    5s
    Click Documents Tab
    Sleep    2s
    Capture Page Screenshot    after_documents_click.png
    Open Subfolder By Name    ${year_folder}    ${month_folder}


Debug Dump Document Viewer HTML
    ${html}=    Execute Javascript    return document.body.innerHTML;
    Create File    ${EXECDIR}/document_viewer_debug.html    ${html}
    Log    ⚠️ Could not find a close button automatically — dumped HTML to document_viewer_debug.html for review.

Click Documents Tab
    ${info}=    Execute Javascript
    ...    var matches = [];
    ...    var els = document.querySelectorAll('*');
    ...    for (var i=0;i<els.length;i++){
    ...        if (els[i].textContent.trim() === 'Documents' && els[i].children.length === 0){
    ...            matches.push(els[i]);
    ...        }
    ...    }
    ...    var target = null;
    ...    for (var j=0;j<matches.length;j++){
    ...        if (matches[j].offsetParent !== null){ target = matches[j]; break; }
    ...    }
    ...    if(!target && matches.length > 0){ target = matches[0]; }
    ...    if(!target) return 'NO MATCH FOUND';
    ...    var r = target.getBoundingClientRect();
    ...    var desc = 'tag=' + target.tagName + ' visible=' + (target.offsetParent !== null)
    ...        + ' rect=(' + Math.round(r.top) + ',' + Math.round(r.left) + ',' + Math.round(r.width) + ',' + Math.round(r.height) + ')'
    ...        + ' html=' + target.outerHTML.substring(0, 200);
    ...    target.click();
    ...    return desc;
    Log    🔍 Documents click target: ${info}


Move Invoice To Processed Folder
    [Arguments]    ${invoice}
    Create Directory    ${INVOICE_PROCESSED_PATH}
    Move File    ${INVOICE_SOURCE_PATH}\\${invoice}    ${INVOICE_PROCESSED_PATH}\\${invoice}
    Log    📦 Moved ${invoice} → ${INVOICE_PROCESSED_PATH}



Click Batch Upload Icon
    Execute Javascript
    ...    var els = document.querySelectorAll('a, button, span, ins, i, div');
    ...    for(var i=0; i<els.length; i++){
    ...        var cls = (els[i].className || '').toLowerCase();
    ...        var title = (els[i].title || '').toLowerCase();
    ...        if((cls.includes('batch') || cls.includes('scan') || cls.includes('upload')
    ...            || title.includes('batch') || title.includes('scan') || title.includes('upload'))
    ...            && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    3s
    Capture Page Screenshot    after_batch_icon_click.png



Close Right Panel
    Execute Javascript
    ...    var els = document.querySelectorAll('button, span, a, div');
    ...    for(var i=0; i<els.length; i++){
    ...        var txt = els[i].textContent.trim();
    ...        var cls = (els[i].className || '').toLowerCase();
    ...        if((txt === '×' || txt === 'x' || txt === 'X' || cls.includes('close'))
    ...            && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    5s

Double Click Uploading Folder
    Double Click Element    xpath=//span[text()='Uploading'] | //div[text()='Uploading'] | //p[text()='Uploading']
    Sleep    2s
    #Capture Page Screenshot    after_uploading_folder_click.png

Click Upload Button In Batch Screen
    Execute Javascript
    ...    var els = document.querySelectorAll('button, a, span, div');
    ...    for(var i=0; i<els.length; i++){
    ...        var txt = els[i].textContent.trim().toUpperCase();
    ...        if(txt === 'UPLOAD' && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    2s
    Capture Page Screenshot    after_upload_button_click.png

Type Path And Press Enter In File Dialog
    Sleep    1s
    # PATH FIX: was a hardcoded personal path (C:\Users\ctn_ravi\Downloads\dms_bot\file_dialog.py)
    # with no arguments. Repointed to the existing robot_scripts/file_dialog.py (already used by
    # the current dms_upload.robot) and now passes INVOICE_SOURCE_PATH explicitly instead of
    # relying on that script's DEFAULT_FOLDER fallback.
    ${result}=    Run Process    python
    ...    ${CURDIR}${/}file_dialog.py
    ...    ${INVOICE_SOURCE_PATH}
    ...    stdout=PIPE    stderr=PIPE
    Log    STDOUT: ${result.stdout}
    Log    STDERR: ${result.stderr}
    Log To Console    STDOUT: ${result.stdout}
    Log To Console    STDERR: ${result.stderr}
    Sleep    3s
    Capture Page Screenshot    after_path_enter.png


Close Upload Success Popup
    Execute Javascript
    ...    var els = document.querySelectorAll('button, span, a, div');
    ...    for(var i=0; i<els.length; i++){
    ...        var txt = els[i].textContent.trim();
    ...        var cls = (els[i].className || '').toLowerCase();
    ...        if((txt === '×' || txt === 'X' || cls.includes('close'))
    ...            && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    2s
    Press Keys    NONE    SPACE
    Sleep    2s
    Capture Page Screenshot    after_popup_close.png

Select All And Index Files
    Sleep    1s
    # Click Select All button visible on the toolbar
    Execute Javascript
    ...    var els = document.querySelectorAll('button, a, span, div');
    ...    for(var i=0; i<els.length; i++){
    ...        var txt = els[i].textContent.trim().toUpperCase();
    ...        if(txt === 'SELECT ALL' && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    2s
    Capture Page Screenshot    after_select_all.png
    # Check Delete On Index checkbox
    Execute Javascript
    ...    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    ...    for(var i=0; i<checkboxes.length; i++){
    ...        var label = document.querySelector('label[for="' + checkboxes[i].id + '"]');
    ...        if(label && label.textContent.trim().toUpperCase().includes('DELETE ON INDEX')){
    ...            if(!checkboxes[i].checked){ checkboxes[i].click(); }
    ...            break;
    ...        }
    ...    }
    Sleep    1s
    Log To Console    ✅ Delete On Index checked
    Capture Page Screenshot    after_delete_checkbox.png
    # Click Index button
    Execute Javascript
    ...    var els = document.querySelectorAll('button, a, input[type="button"]');
    ...    for(var i=0; i<els.length; i++){
    ...        var txt = els[i].textContent.trim().toUpperCase();
    ...        if(txt === 'INDEX' && els[i].offsetParent !== null){
    ...            els[i].click();
    ...            break;
    ...        }
    ...    }
    Sleep    3s
    Capture Page Screenshot    after_index_click.png



Index Each File
    [Arguments]    ${report_name}
    Sleep    2s
    # Select CVReports from Document Type dropdown
    Execute Javascript
    ...    var selects = document.querySelectorAll('select');
    ...    for(var i=0; i<selects.length; i++){
    ...        var opts = selects[i].options;
    ...        for(var j=0; j<opts.length; j++){
    ...            if(opts[j].text.trim() === 'CVReports'){
    ...                selects[i].selectedIndex = j;
    ...                selects[i].dispatchEvent(new Event('change', {bubbles:true}));
    ...                break;
    ...            }
    ...        }
    ...    }
    Sleep    2s
    # Fill ReportName field
    Wait Until Element Is Visible
    ...    xpath=//*[contains(text(),'ReportName')]/ancestor::tr[1]//input    10s
    ${input_el}=    Get WebElement
    ...    xpath=//*[contains(text(),'ReportName')]/ancestor::tr[1]//input
    Clear Element Text    ${input_el}
    Input Text    ${input_el}    ${report_name}
    Sleep    1s
    # Check Retain checkbox
    Execute Javascript
    ...    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    ...    for(var i=0; i<checkboxes.length; i++){
    ...        var label = document.querySelector('label[for="' + checkboxes[i].id + '"]');
    ...        if(label && label.textContent.trim().toUpperCase().includes('RETAIN')){
    ...            if(!checkboxes[i].checked){ checkboxes[i].click(); }
    ...            break;
    ...        }
    ...    }
    Sleep    1s
    Log To Console    ✅ Retain checked for ${report_name}
    # Click Create button
    Wait Until Element Is Visible    xpath=//button[normalize-space()='Create']    10s
    Execute Javascript
    ...    var els = document.querySelectorAll('button');
    ...    for(var i=0; i<els.length; i++){
    ...        if(els[i].textContent.trim() === 'Create' && els[i].offsetParent !== null){
    ...            els[i].click(); break;
    ...        }
    ...    }
    Sleep    5s
    Capture Page Screenshot    after_create_${report_name}.png
    Log To Console    ✅ Created document: ${report_name}

Move All Files To Processed Folder
    Create Directory    ${INVOICE_PROCESSED_PATH}
    ${files}=    List Files In Directory    ${INVOICE_SOURCE_PATH}    *.pdf    absolute=True
    Log To Console    📁 Files to move: ${files}
    FOR    ${file}    IN    @{files}
        ${filename}=    Evaluate    __import__('os').path.basename(r'${file}')
        ${dest}=    Set Variable    ${INVOICE_PROCESSED_PATH}\\${filename}
        Run Process    cmd    /c    move    /Y    ${file}    ${dest}
        Log To Console    📦 Moved ${filename} → Folder_2
    END


Click View On Document Created Popup
    ${popup_found}=    Run Keyword And Return Status
    ...    Wait Until Element Is Visible
    ...    xpath=//*[contains(text(),'Document created successfully')]    10s

    IF    ${popup_found}
        Log    🟢 Document created popup found — clicking Navigate
        Click Element    xpath=//button[normalize-space()='Navigate']
        Sleep    10s
    ELSE
        Log    ⚠️ Document created popup not found
    END



Select Document Row By Name
    [Arguments]    ${report_name}
    Wait Until Element Is Visible
    ...    xpath=//*[normalize-space(text())='${report_name}']    10s
    Sleep    1s

    ${status}=    Execute Javascript
    ...    var target = null;
    ...    var candidates = document.querySelectorAll('a, span, td, div');
    ...    for (var i=0; i<candidates.length; i++){
    ...        if (candidates[i].textContent.trim() === '${report_name}'){
    ...            target = candidates[i];
    ...            break;
    ...        }
    ...    }
    ...    if(!target) return 'ROW_NOT_FOUND';
    ...    var row = target.closest('tr');
    ...    if(!row) return 'TR_NOT_FOUND';
    ...    var checkbox = row.querySelector('input[type="checkbox"]');
    ...    if(!checkbox){
    ...        var firstCell = row.querySelector('td');
    ...        if(firstCell){ checkbox = firstCell.querySelector('input, span, div'); }
    ...    }
    ...    if(!checkbox) return 'CHECKBOX_NOT_FOUND';
    ...    if(checkbox.tagName === 'INPUT' && !checkbox.checked){
    ...        checkbox.click();
    ...    } else if (checkbox.tagName !== 'INPUT') {
    ...        checkbox.click();
    ...    }
    ...    return 'OK';

    Log To Console    ☑️ Select row status for '${report_name}': ${status}
    Should Be Equal As Strings    ${status}    OK
    ...    msg=Could not select checkbox for document '${report_name}' — got status: ${status}
    Sleep    1s


Deselect Document Row By Name
    [Arguments]    ${report_name}
    ${status}=    Execute Javascript
    ...    var target = null;
    ...    var candidates = document.querySelectorAll('a, span, td, div');
    ...    for (var i=0; i<candidates.length; i++){
    ...        if (candidates[i].textContent.trim() === '${report_name}'){
    ...            target = candidates[i];
    ...            break;
    ...        }
    ...    }
    ...    if(!target) return 'ROW_NOT_FOUND';
    ...    var row = target.closest('tr');
    ...    if(!row) return 'TR_NOT_FOUND';
    ...    var checkbox = row.querySelector('input[type="checkbox"]');
    ...    if(!checkbox){
    ...        var firstCell = row.querySelector('td');
    ...        if(firstCell){ checkbox = firstCell.querySelector('input, span, div'); }
    ...    }
    ...    if(!checkbox) return 'CHECKBOX_NOT_FOUND';
    ...    if(checkbox.tagName === 'INPUT' && checkbox.checked){
    ...        checkbox.click();
    ...    } else if (checkbox.tagName !== 'INPUT') {
    ...        checkbox.click();
    ...    }
    ...    return 'OK';

    Log To Console    ☐ Deselect row status for '${report_name}': ${status}
    Sleep    1s


Close Any Open Context Menu
    Execute Javascript
    ...    document.body.click();
    Sleep    1s
    Press Keys    NONE    ESCAPE
    Sleep    1s


Right Click Document Row And Open Send To
    [Arguments]    ${report_name}

    # Clean up any leftover menu from the previous file before starting
    Close Any Open Context Menu

    ${locator}=    Set Variable
    ...    xpath=//*[normalize-space(text())='${report_name}']

    Wait Until Element Is Visible    ${locator}    10s
    Scroll Element Into View    ${locator}
    ${row_element}=    Get WebElement    ${locator}

    # Attempt 1: Selenium's native context menu (real right-click)
    Open Context Menu    ${row_element}
    Sleep    2s

    # Tag the visible "Send To" element with a unique id we control
    ${tag_result}=    Execute Javascript
    ...    var candidates = document.querySelectorAll('*');
    ...    var target = null;
    ...    for (var i=0; i<candidates.length; i++){
    ...        var txt = candidates[i].textContent.trim();
    ...        if (txt === 'Send To' && candidates[i].offsetParent !== null){
    ...            target = candidates[i];
    ...            break;
    ...        }
    ...    }
    ...    if(!target) return 'NOT_FOUND';
    ...    var el = target;
    ...    var safeguard = 0;
    ...    while (el && safeguard < 6){
    ...        var rect = el.getBoundingClientRect();
    ...        if (rect.width > 0 && rect.height > 0){
    ...            break;
    ...        }
    ...        el = el.parentElement;
    ...        safeguard++;
    ...    }
    ...    if(!el) return 'NOT_FOUND';
    ...    el.id = 'cv_send_to_target';
    ...    return 'TAGGED';

    Log To Console    📤 Send To tag result: ${tag_result}

    # Attempt 2 (fallback): if native right-click didn't open the menu, dispatch contextmenu event via JS
    IF    '${tag_result}' == 'NOT_FOUND'
        Log To Console    ⚠️ Native right-click didn't reveal 'Send To', retrying with JS contextmenu event
        Execute Javascript
        ...    var target = null;
        ...    var candidates = document.querySelectorAll('*');
        ...    for (var i=0; i<candidates.length; i++){
        ...        if (candidates[i].textContent.trim() === '${report_name}' && candidates[i].offsetParent !== null){
        ...            target = candidates[i];
        ...        }
        ...    }
        ...    if(target){
        ...        var rect = target.getBoundingClientRect();
        ...        var evt = new MouseEvent('contextmenu', {
        ...            bubbles: true, cancelable: true, view: window,
        ...            clientX: rect.left + 5, clientY: rect.top + 5, button: 2
        ...        });
        ...        target.dispatchEvent(evt);
        ...    }
        Sleep    2s

        ${tag_result}=    Execute Javascript
        ...    var candidates = document.querySelectorAll('*');
        ...    var target = null;
        ...    for (var i=0; i<candidates.length; i++){
        ...        var txt = candidates[i].textContent.trim();
        ...        if (txt === 'Send To' && candidates[i].offsetParent !== null){
        ...            target = candidates[i];
        ...            break;
        ...        }
        ...    }
        ...    if(!target) return 'NOT_FOUND';
        ...    var el = target;
        ...    var safeguard = 0;
        ...    while (el && safeguard < 6){
        ...        var rect = el.getBoundingClientRect();
        ...        if (rect.width > 0 && rect.height > 0){
        ...            break;
        ...        }
        ...        el = el.parentElement;
        ...        safeguard++;
        ...    }
        ...    if(!el) return 'NOT_FOUND';
        ...    el.id = 'cv_send_to_target';
        ...    return 'TAGGED';

        Log To Console    📤 Send To tag result (retry): ${tag_result}
    END

    Should Be Equal As Strings    ${tag_result}    TAGGED
    ...    msg=Could not find a visible 'Send To' menu item in the context menu for '${report_name}'

    # NEW APPROACH: skip real mouse hover entirely (Edge WebDriver DPI/coordinate bug
    # causes MoveTargetOutOfBoundsException regardless of element size/position).
    # Instead, find "Generate Document link" directly in the DOM (even while hidden)
    # and force every ancestor's CSS to make it visible — no hover needed.
    ${force_result}=    Execute Javascript
    ...    var candidates = document.querySelectorAll('*');
    ...    var genLink = null;
    ...    for (var i=0; i<candidates.length; i++){
    ...        if (candidates[i].textContent.trim() === 'Generate Document link'
    ...            && candidates[i].children.length === 0){
    ...            genLink = candidates[i];
    ...            break;
    ...        }
    ...    }
    ...    if(!genLink) return 'GENLINK_NOT_FOUND';
    ...    var el = genLink;
    ...    var count = 0;
    ...    while (el && count < 8){
    ...        el.style.setProperty('display', 'block', 'important');
    ...        el.style.setProperty('visibility', 'visible', 'important');
    ...        el.style.setProperty('opacity', '1', 'important');
    ...        el.style.setProperty('max-height', 'none', 'important');
    ...        el.classList.remove('hidden');
    ...        el.classList.remove('hide');
    ...        el.classList.remove('collapsed');
    ...        el = el.parentElement;
    ...        count++;
    ...    }
    ...    genLink.id = 'cv_gen_doc_link_target';
    ...    return 'FORCED';

    Log To Console    🔓 Force-show Generate Document link result: ${force_result}

    IF    '${force_result}' == 'GENLINK_NOT_FOUND'
        Capture Page Screenshot    send_to_failure_${report_name}.png
        ${html}=    Execute Javascript    return document.body.innerHTML;
        Create File    ${EXECDIR}/send_to_failure_${report_name}.html    ${html}
        Log    ⚠️ Dumped page HTML/screenshot for debugging: send_to_failure_${report_name}
    END

    Should Be Equal As Strings    ${force_result}    FORCED
    ...    msg=Could not find/force-show 'Generate Document link' for '${report_name}'
    Sleep    1s


Click Generate Document Link
    ${click_status}=    Execute Javascript
    ...    var el = document.getElementById('cv_gen_doc_link_target');
    ...    if(!el) return 'NOT_FOUND';
    ...    el.click();
    ...    return 'CLICKED';
    Log To Console    🔗 Generate Document link click status: ${click_status}
    Should Be Equal As Strings    ${click_status}    CLICKED
    ...    msg=Could not click 'Generate Document link'
    Sleep    2s


Copy Generated Link And Close Popup
    Wait Until Element Is Visible
    ...    xpath=//*[contains(text(),'openDocumentLogin')] | //input[contains(@value,'openDocumentLogin')]    10s

    ${doc_link}=    Execute Javascript
    ...    var inputs = document.querySelectorAll('input, textarea');
    ...    for (var i=0; i<inputs.length; i++){
    ...        if (inputs[i].value && inputs[i].value.indexOf('openDocumentLogin') > -1){
    ...            return inputs[i].value;
    ...        }
    ...    }
    ...    var els = document.querySelectorAll('div, span, p, td');
    ...    for (var j=0; j<els.length; j++){
    ...        if (els[j].textContent && els[j].textContent.indexOf('openDocumentLogin') > -1){
    ...            return els[j].textContent.trim();
    ...        }
    ...    }
    ...    return 'NOT_FOUND';

    Log To Console    🔗 Generated Link: ${doc_link}

    ${ok_clicked}=    Run Keyword And Return Status
    ...    Click Element    xpath=//button[normalize-space()='Ok']

    IF    not ${ok_clicked}
        Log To Console    ⚠️ Native click on 'Ok' failed — trying JS click
        Execute Javascript
        ...    var buttons = document.querySelectorAll('button');
        ...    for (var i=0; i<buttons.length; i++){
        ...        if (buttons[i].textContent.trim() === 'Ok' && buttons[i].offsetParent !== null){
        ...            buttons[i].click();
        ...            break;
        ...        }
        ...    }
    END
    Sleep    2s

    [Return]    ${doc_link}


Save File Name And Link To Excel
    [Arguments]    ${file_name}    ${doc_link}
    # PATH FIX: was calling a hardcoded personal path (C:\Users\ctn_ravi\Downloads\dms_bot\
    # excel_writer.py) with only 2 args -- writing to that script's own hardcoded personal
    # EXCEL_PATH default, which services/dms_links_import.py never reads from. Repointed to
    # the app's config-driven robot_scripts/dms_excel_writer.py, passing DMS_LINKS_EXCEL_PATH
    # explicitly as the 3rd arg (see that script's own docstring for why this matters).
    ${result}=    Run Process    python
    ...    ${CURDIR}${/}dms_excel_writer.py
    ...    ${file_name}    ${doc_link}    ${DMS_LINKS_EXCEL_PATH}
    ...    stdout=PIPE    stderr=PIPE
    Log    STDOUT: ${result.stdout}
    Log    STDERR: ${result.stderr}
    Log To Console    📊 Saved to Excel: ${file_name} → ${doc_link}


Generate And Save Document Link
    [Arguments]    ${report_name}
    Select Document Row By Name    ${report_name}
    Right Click Document Row And Open Send To    ${report_name}
    Click Generate Document Link
    ${doc_link}=    Copy Generated Link And Close Popup
    Save File Name And Link To Excel    ${report_name}    ${doc_link}
    Deselect Document Row By Name    ${report_name}


Process All Document Links
    [Arguments]    @{report_names}
    FOR    ${report_name}    IN    @{report_names}
        Log To Console    ▶️ Processing link for: ${report_name}
        Generate And Save Document Link    ${report_name}
    END
*** Test Cases ***
MIP Create Year And Month Folder
    # Step 1: Login
    Open Login Page
    Login To Contentverse

    # Step 2: Get year and month folder names
    ${year_folder}=     Get Current Year Folder Name
    ${month_folder}=    Get Current Month Folder Name
    Log    📁 Year folder: ${year_folder}
    Log    📁 Month folder: ${month_folder}

    # Step 3: Expand tree
    Expand Material Inward Process
    Expand MIP Docs

    # Step 4a: Create YEAR folder under MIP Docs if missing (auto-expands MIP Docs first, then scoped check)
    Create Subfolder If Not Exists
    ...    xpath=//*[contains(text(),'MIP Docs')]    MIP Docs    ${year_folder}
    # Step 4b: Open year folder (scoped to MIP Docs so it opens the right node, not a random duplicate)
    Open Subfolder By Name    MIP Docs    ${year_folder}

    # Step 4c: Create MONTH folder inside year folder if missing
    Create Subfolder If Not Exists
    ...    xpath=//*[text()='${year_folder}']    ${year_folder}    ${month_folder}

    # Step 5: Open month folder
    Open Subfolder By Name    ${year_folder}    ${month_folder}
    ${invoice_list}=    Get List Of Invoice Files

    # Build the list of report names BEFORE files get moved out of the source folder
    @{report_names}=    Create List
    FOR    ${invoice}    IN    @{invoice_list}
        ${report_name}=    Evaluate    __import__('os').path.splitext('${invoice}')[0]
        Append To List    ${report_names}    ${report_name}
    END

    # Open Batch Indexing / Scanning for bulk upload
    Click Batch Upload Icon
    Close Right Panel
    Double Click Uploading Folder
    Click Upload Button In Batch Screen
    Type Path And Press Enter In File Dialog
    Close Upload Success Popup

    Select All And Index Files
    ${invoice_list}=    Get List Of Invoice Files
    FOR    ${invoice}    IN    @{invoice_list}
        ${report_name}=    Evaluate    __import__('os').path.splitext('${invoice}')[0]
        Index Each File    ${report_name}
    END
    Move All Files To Processed Folder

    # Popup appears once, after all files are indexed → click Navigate to return to folder view
    Click View On Document Created Popup

    # Step 6: For every uploaded file, generate its document link and save to Excel
    Process All Document Links    @{report_names}

    # INTEGRATION FIX: this marker was missing entirely in the draft as received.
    # services/dms_upload_runner.py.run_dms_upload() checks stdout for the exact
    # string "RESULT:DMS_UPLOAD_STATUS:SUCCESS" (see its `if "RESULT:DMS_UPLOAD_STATUS:
    # SUCCESS" not in output` check) before marking any record's dms_status='uploaded'
    # or running the DB link import -- without this line, every run would be treated
    # as a failure regardless of whether the upload actually worked, and dms_status
    # would never advance past 'staged'.
    Log To Console    RESULT:DMS_UPLOAD_STATUS:SUCCESS
